// Type declarations for JSON imports
declare module '*.json' {
  const value: unknown;
  export default value;
}

// Generated by scripts/build-data.js
declare module '*/generated/roots.json' {
  const value: string[];
  export default value;
}

declare module '*/generated/rootAliases.json' {
  const value: Record<string, string>;
  export default value;
}

declare module '*/generated/rootEntries.json' {
  interface GeneratedRootEntry {
    meaning: string;
    hint: string;
    examples: string;
    difficulty: 'easy' | 'medium' | 'hard';
    successMessage: string;
    poetryExample: string;
  }
  const value: Record<string, GeneratedRootEntry>;
  export default value;
}
